version: '3.8'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ../Dockerfile_frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
        environment:
            - REACT_APP_BACKEND_URL=http://backend:8000
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: ../Dockerfile_backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        environment:
            - DATABASE_URL=postgres://user:password@db:5432/mydatabase
        depends_on:
            - db

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: dbname
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
