version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: ../Dockerfile_frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
        environment:
            - REACT_APP_BACKEND_URL=http://backend:8000
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: ../Dockerfile_backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        environment:
            - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
            - TEST_DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@test_db:5432/test_db
            - FLASK_APP=src/__init__.py
        depends_on:
            - db
            - test_db

    db:
        image: postgres:12
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    test_db:
        image: postgres:12
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: test_db
        ports:
            - "5433:5432"
        volumes:
            - test_pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
    test_pgdata:
