FROM python:3.7

# make app dir
WORKDIR /app

# pip instarll
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy other code
COPY . .

# start app
CMD ["python", "sample.py"]
